// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNeMS28evQm6t2kWt_KxKauZ6OVy1QygA',
    appId: '1:726180696113:web:f3c6124148f793015b0510',
    messagingSenderId: '726180696113',
    projectId: 'skipncall-1d5ef',
    authDomain: 'skipncall-1d5ef.firebaseapp.com',
    storageBucket: 'skipncall-1d5ef.appspot.com',
    measurementId: 'G-D0C19J4L54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuFvYV9ZbwfQrJpA-XFeoDxG6s_cqJjiM',
    appId: '1:726180696113:android:9bf2074f2840ee925b0510',
    messagingSenderId: '726180696113',
    projectId: 'skipncall-1d5ef',
    storageBucket: 'skipncall-1d5ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0nUMBe8KF9ZPv2ri3OTv1253PrAROoWg',
    appId: '1:726180696113:ios:63e864d1e68e66a95b0510',
    messagingSenderId: '726180696113',
    projectId: 'skipncall-1d5ef',
    storageBucket: 'skipncall-1d5ef.appspot.com',
    iosBundleId: 'com.example.skipncall.skipNCall',
  );
}
